### ISSUE TITLE
gauge default maxValue causes panic

### ISSUE THREAD

**Issue by fc92** [navidys/tvxwidgets#2]
**Describe the bug**
gauge maxValue can be zero, causing panic with divide by zero

**To Reproduce**
Initialize gauge without setting maxValue
Draw

**Expected behavior**
The initialization should never allow zero value for gauge max value.

**Desktop:**
 - OS Ubuntu 22.04.1 LTS, Linux  5.15.39-051539-generic #202205120747 SMP Thu May 12 12:51:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - go version go1.19.2 linux/amd64
 - tview version github.com/rivo/tview v0.0.0-20220916081518-2e69b7385a37

**Comment by navidys** [comment]
Hi @fc92 
Thanks for raising the issue, its fixed now.
 
Regards
