### ISSUE TITLE
Line charts

### ISSUE THREAD

**Issue by darkhz** [navidys/tvxwidgets#3]
It would be useful if line charts and/or sparkline charts are implemented in this library, to better represent a dataset or multiple datasets. Do look at [termui](https://github.com/gizak/termui/) for reference. 

Many people have requested support to render line charts in the tview repo, but the author is planning it for v2 ([here](https://github.com/rivo/tview/issues/11)). Since you already support custom widgets, perhaps you could add support for this too?

The source for the relevant widgets are here:
- [Plot (for line charts)](https://github.com/gizak/termui/blob/master/widgets/plot.go)
- [Sparkline](https://github.com/gizak/termui/blob/master/widgets/sparkline.go)

**Comment by navidys** [comment]
Hi @darkhz 

Sure will look into it.

**Comment by navidys** [comment]
@darkhz 
line chart and scatter plot has been added (#5)

![screenshot](https://user-images.githubusercontent.com/5696685/207294456-8e1b2622-752a-4bc5-892c-e882abcb7688.png)

will add sparkline in different PR.

**Comment by darkhz** [comment]
On behalf of everyone who requested this feature, thank you very much. This is a very useful and much needed widget for tview. I will test this on my end, and will reopen this issue again, should any issues arise with the implementation.

**Comment by navidys** [comment]
added sparkline widget as well #6 .

**Comment by darkhz** [comment]
Very good. Will test it later. Thank you.

**Comment by Fyb3roptik** [comment]
How can we adjust the bottom bar numbers? Would love to put custom attributes there instead

**Comment by navidys** [comment]
@Fyb3roptik 
at the moment not possible, will add the feature soon.

**Comment by Fyb3roptik** [comment]
I actually accomplished this using frames. Looks slick!

**Comment by navidys** [comment]
@Fyb3roptik nice, would you be intrested to PR it ?

**Comment by Fyb3roptik** [comment]
Once I'm free sure! Bogged down atm
