### ISSUE TITLE
Is there any way to render charts without handing over the entire terminal?

### ISSUE THREAD

**Issue by anderspitman** [navidys/tvxwidgets#41]
I'm trying to add a few charts to my app, but still allow normal stdout/stderr logs to be shown. Is this possible with tvxwidgets?

**Comment by navidys** [comment]
Hi @anderspitman 

I don't think it will be possible since tvxwidgets is part tview, the only way I can think of is to use textarea widget from tview and display your stderr and stdout into it.

**Comment by anderspitman** [comment]
Makes sense; thanks @navidys!
