### ISSUE TITLE
Any way to get the inner width/height of a chart?

### ISSUE THREAD

**Issue by anderspitman** [navidys/tvxwidgets#42]
This library is awesome and I'm finding it a joy to work with. Thank you!

I'm trying to create a line chart that gets updated in real time. So the rightmost value represents the latest data, with old data scrolling off the left of the chart. I'm having trouble aligning the latest data to the right edge though. Ideally I need to know exactly how many points can be displayed, so I can calculate how much data to hand to SetData. The width of chart Box is close, but it's not exact because of the axes.

I looked through the API and didn't find any obvious way to do this. The demo with updating charts simply shows more sin data when I make it larger, ie it doesn't have this alignment problem.

**Comment by navidys** [comment]
Hi @anderspitman 

By inner width/height you mean the width and height of the chart drawing area without the X and Y axis ?

**Comment by anderspitman** [comment]
Yes exactly. The Y axis in particular varies in size depending on how many characters are necessary to draw the axis values. Currently I'm working around this with a small function that reverse engineers the width of the axis.

**Comment by navidys** [comment]
I will add the feature to the charts.
Are you interested to create a feature and PR ?

**Comment by anderspitman** [comment]
I'll take a look

**Comment by anderspitman** [comment]
@navidys looks like you have things nicely broken into functions already. I'm happy to make a PR for this. I think the simplest way to achieve what I need would be to make `getYAxisLabelsWidth` public, possibly renaming it. Alternatively I could add a method such as `GetPlotRect` which would return the inner dimensions minus any axes size.

Which would you prefer, or something else?

EDIT: Looks like you already have `getChartAreaRect` as well. Very nice.

**Comment by navidys** [comment]
Hi @anderspitman 

Thanks for this, GetPlotRect looks good what do you think think ?

**Comment by anderspitman** [comment]
That would work for me. I believe the simplest implementation would be to rename `getChartAreaRect` to `GetPlotRect`. Does that sound good?

**Comment by navidys** [comment]
Yes sure it sounds good

**Comment by anderspitman** [comment]
Alright I opened #44. Let me know if it needs any changes
