### ISSUE TITLE
Set y axis scale?

### ISSUE THREAD

**Issue by anderspitman** [navidys/tvxwidgets#43]
Is it possible to set the Y axis scale, rather than have it automatically set from the data?

**Comment by navidys** [comment]
You can set the the rect size (x, y, width, height) of the chart box using `SetRect` function, is this solving your issue ?

**Comment by anderspitman** [comment]
Sorry, I was ambiguous. I meant the axis values. So for example if my data is [ 1, 2, 3 ] the Y axis will go from 1-3. Is there a way for me to force it to show 1-10, even though none of my values are over 3?

**Comment by navidys** [comment]
Hi @anderspitman 
At this stage no , it doesn't support scaling, I might add the feature as well but on some of the charts , which chart widget are you using in your app ?

**Comment by anderspitman** [comment]
I'm making a dashboard that primarily displays values over time, so line charts are the most important for me.

**Comment by anderspitman** [comment]
@navidys I might actually be able to do this as well. Do you want me to take a look?

**Comment by navidys** [comment]
@anderspitman sure why not , thanks

**Comment by markusressel** [comment]
I am interested in this functionality as well. I am using your project in [fan2go-tui](https://github.com/markusressel/fan2go-tui), and some of the graphs have a predefined range, f.ex. 0-255.

**Comment by anderspitman** [comment]
For my part, unfortunately I got distracted by other projects and haven't been working on TUI lately. I want to make it back but not sure at what point that might happen.

**Comment by markusressel** [comment]
@navidys could you remove the "stale" label from this issue? Its definitely not stale anymore now :smile:
