### ISSUE TITLE
MessageDialog setTitle(...) method does not work

### ISSUE THREAD

**Issue by greybackcodemonkey** [navidys/tvxwidgets#50]
MessageDialog component setTitle(...) method does not work.
This can be reproduced by just running default tvxwidget demo for the dialog.

Tested on:
go 1.22
tvxwidgets: v0.6.0 (with default dependencies using go mod tidy)

Issue is probably caused by displaying border of 'layout' field in MessageDialog struct, but using default SetTitle(...) from embedded Box

I'm assuming this is not a desired behavior, as preview image from demo folder displays working title

**Comment by navidys** [comment]
Hi @greybackcodemonkey 

Thanks for that , will have a fix soon.
