### ISSUE TITLE
Mispelling in function name

### ISSUE THREAD

**Issue by Fyb3roptik** [navidys/tvxwidgets#7]
https://github.com/navidys/tvxwidgets/blob/main/plot.go#L222

This function name is misspelled :)

**Comment by navidys** [comment]
Hey @Fyb3roptik 
Thanks for pickup. Will fix it soon, or if you like you can PR it as well.

**Comment by Fyb3roptik** [comment]
https://github.com/navidys/tvxwidgets/pull/8

**Comment by navidys** [comment]
Thanks

**Comment by Fyb3roptik** [comment]
No worries! Great repo! It has made my lovely new media server software so pretty
